kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgC8I/6d4L7T3675T0ymRWgY9zqEh0pKOKuScdLij4AUEOX2nswDH/B+Q0MlMdNgzD8OFQvEWZg9uyFGNMtIbrve7BuqYCIje1eMgTET4DbSPKS32SqWyc/Tliba1lCFXYusL7bVML3aH7beapK6JIlOMLfjzjedDOQWLbtRclYxt2gX67rcyoUytox170okLd4cFYIyHfAbeyKQYTzRBXyQ9iBEKmmvuICAE99G4TAj247nL1rStiLGaN6fC3w+IQEdzjfMLnwQcHfZ7vkVxQgmHjcI8RrPgYUYiDs1pWO62g/+Z/dCOd6GFgWHA6h5ro+VRYaYKsPUw76bTQkZQSXWP93BYXmd0t5x1OwbGjK1vC7Ug+DJFOu3qHYrwU3dfFoev6i0W20HtuP8Rjh2MBD78xloozXPWl10IKLOsK6028zC2E8crWbxm4ou5aic30GJMcYeQ9/E5SltmCueHjWGaMR49SPguz9SEvZpdk5hZU6NfdmoCVnj31Gz9adeThErO4ILkXcyyQIvE8ZRU867FhqXcij/lCwusA7uGwSqLqIexHGTg9FbteS0TReVRBveWwU8j0Kv1H4aYNU/NDCVEnVgCgi5zn5YiHAuP+nNg/lOZmMZ+PpqFQoNOEZkpove/DiBD67VEHUREPHkZwkDPO9mv6UfWeFTirBUlZVMa/VAG0BVvB2UFa1Z3XMMh7pNUw61VoaSDEfT96Q=
    admin-user: AgBAB/3CBlfrBGFFo96IZMZPskgHZ6zLyxYI7s8gm1F6Z/RdJNbuK/WZ4pTAI+IqsHnay5XrVo/VG8C0q0T64vCX1wGirj2HR7e9rUr2FuQkUV8kM2FseyiWwkVrsNLgpsRs99XWYYMgo5NxMrrVIaGlRiVQzERZKqEsMcaUJeiu3hB3K2d8zjwS6w0s/vcdnR/D3q/mTLJ3LEKZRhqPUMtcgKNwFe5mD7fIJKmEzOZOA5KDAQlqpzwWzfjt6wqARdzKcjBnmBT6sxBYY+vI61W62+LzaeuF2Vf5KVnDcbjIkYgWR7i+5eZqAsJzSbpk3LkNb6KwItU7WGv7ulHGjrnstPtVDHnrZgekIBYC07FgKWAYfzmH1Xy9D7mtN4W6cUtQO8N1pHPudZ+bL1jtzts6NpjrV6As6gJLTSi+T5TkEFEvooGVNHEBZ2bhIMyRKDRmovPatZTEA3o9MsmVRE9N83FzQIMIksJDW69D1HFmFiQLxwUle20UQqaTa+BbAcRx9hxqKDoUmVAoD0rO259J4izzltXIwy0mux3ewCVPCzmjj6YriNq9Xcv2ijqltzeXkfcWHql6UtZg+dXMFzJeBnyLqHiJeUldKr22Xy0EutoXZ5C70YiH77ghJuNluC/pQfB/2kzrAg404A01smiUaHSadnS88RwFJgmhAsV9jkZpL/tHa78OCAtX5cAMI9ttexrcxA==
